name: Update WakaTime section

on:
  schedule:
    # 05:30 UTC daily
    - cron: "30 5 * * *"
  workflow_dispatch:

jobs:
  waka:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          TARGET_PATH: README.md
